Allow configurable GeoIP database path #33
enonic/lib-geoip pull request #34
Opened 2022-11-23 15:32 UTC by anatol-sialitski

2022-11-23 15:59 UTC, rymsha approved these changes

2022-11-23 17:17 UTC, alansemenov approved these changes

2022-11-23 18:57 UTC, rymsha requested changes

2022-11-23 18:57 UTC, rymsha commented on build.gradle
> +    implementation "com.enonic.xp:core-api:${xpVersion}"
compileOnly for api is not that bad.

2022-11-23 18:57 UTC, rymsha commented on README.md
> +com.enonic.lib.geoip.database.filepath=/absolute/path/to/database.mmdb
```suggestion
com.enonic.lib.geoip.database.filepath=/path/to/database.mmdb
```

2022-11-23 18:57 UTC, rymsha commented on src/main/java/com/enonic/geoip/DbReader.java
> +        try (Reader r = new Reader( database, FileMode.MEMORY_MAPPED, new CHMCache() ))
Actually it looks extremely inefficient to read the database for every call

2022-11-23 19:04 UTC, rymsha commented on src/main/java/com/enonic/geoip/DbReader.java
> +        try (Reader r = new Reader( database, FileMode.MEMORY_MAPPED, new CHMCache() ))
Maybe re-read only if file timestamp changes?

2022-11-24 21:44 UTC, rymsha approved these changes

2022-11-25 08:25 UTC, merged